# Generated by Django 2.1.7 on 2019-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
