# Generated by Django 2.1.7 on 2019-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
